version: "3.3"
services:
  node:
    image: hookhub/hookhub
    environment:
      - HOOKHUB_BOOTSTRAP_MODULE=hookhub-bootstrap-local
      - HOOKHUB_BOOTSTRAP_SOURCE=https://github.com/hookhub/hookhub-bootstrap-local.git
      - HOOKHUB_BOOTSTRAP_CONFIG=/run/secrets/hookhub.yml
    network_mode: bridge
    secrets:
      - hookhub.yml
    volumes:
    - ./bundle:/app/bundle
secrets:
  hookhub.yml:
    file: ./hookhub.yml
